<?php

include_once('commons_node_links.features.inc');

/**
*
* Implements hook init
*/
function commons_node_links_init() {
  $module_path = drupal_get_path('module', 'commons_node_links');
  drupal_add_css($module_path . '/css/commons_node_links.css');
}



/**
 * Implements hook_theme_registry_alter().
 * 
 * Overrides node_link_style hooks. 
 * 
 */
function commons_node_links_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['node_link_style_custom_group'])) {
    $theme_registry['node_link_style_custom_group']['function'] = 'commons_node_links_custom_group';
  }
  if (isset($theme_registry['node_link_style_custom_group'])) {
    $theme_registry['node_link_style_custom_group_item']['function'] = 'commons_node_links_custom_group_item';
  }
}


/**
* @return
*   HTML for drop down group item.
*/
function commons_node_links_custom_group_item($link, $config, $options) {
  $output = '';
  $list_name=$options['list_name'];
  $first=$options['first'];
  $last=$options['last'];

  //dropdown
  $title_tag=_get_title($link, $config);
  $title_tag=strip_tags($title_tag);
  if ($first) {
    $output .='<li class="node_link_style-dropdown-main">';
    $title_tag='<span>' . $title_tag . '</span>';
  }
  else $output .='<li class="node_link_style-dropdown-item">';
  
  if (isset($link['href']))
    $output .=l($title_tag, $link['href'], $link);
  else {
    //try to extract href from title
    $path=_extract_href($link['title']);
    $output .='<a href="' . $path . '">' . $title_tag . '</a>';
  }
  
  
  if (!$first) $output .='</li>';
  if ($first && !$last) $output .='<ul>';
  elseif ($last && !$first) $output .='</ul>';
  if ($last) $output .='</li>';
  
  return $output;
}

/**
 * @return
 *   HTML for drop down group.
 */
function commons_node_links_custom_group($list_name, $link, $config, $options, $start=TRUE) {
  $output = '';
  if ($start) {
    $drop_down_form_name='drop_down_form_' . $list_name;
    $drop_down_input_name='drop_down_input_' . $list_name;     
     
    //dropdown begin
    $output .='<div class="subscription_clear_style">';
    $output .='<ul class="node_link_style-dropdown">';
  }
  else{
    //dropdown end
    $output .='</ul>';
    $output .='</div>';
}
return $output;
}

/**
 * Extracts href
 * 
 * @param html
 */
function _extract_href($s) {
  $s=strip_tags($s, '<a>');
  $matches=array();
  if (preg_match("/href=\"(.*?)\"/i" , $s, $matches))
      return $matches[1];
  return $s;
}